# Generated by Django 3.1.5 on 2021-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25, verbose_name='姓名')),
                ('pbirthday', models.DateField(verbose_name='出生日期')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
